name: NBTViewer
version: 0.2-SNAPSHOT
author: mathdu07
website: http://mathdu07.github.io/NBTViewer
main: fr.mathdu07.nbtviewer.NBTViewerPlugin
description: Allow you to see NBT of various elements
commands:
  nbtitem:
    description: Print the NBT of the item in your hand
    permission: nbtviewer.item
    aliases: [nbti]
  nbthelp:
    description: Show the help of this plugin
    permission: nbtviewer.help
    aliases: [nbth, "nbt?"]
permissions:
  nbtviewer.*:
    default: false
    children:
      nbtviewer.item: true
      nbtviewer.help: true
      nbtviewer.entity: true
  nbtviewer.item:
    default: op
  nbtviewer.help:
    default: true
  nbtviewer.entity:
    default: op
    
