name: NBTViewer
version: 0.2-SNAPSHOT
author: mathdu07
website: http://mathdu07.github.io/NBTViewer
main: fr.mathdu07.nbtviewer.NBTViewerPlugin
description: Allow you to see NBT of various elements
commands:
  nbtitem:
    description: Print the NBT of the item in your hand
    permission: nbtviewer.item
    aliases: [nbti]
permissions:
  nbtviewer.*:
    default: false
    children:
      nbtviewer.item: true
  nbtviewer.item:
    default: op 
    
